<!DOCTYPE html>
<html lang="en">

	<head>
		<title>Simple MVC</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- css -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
		<link rel="stylesheet" href="/css/style.css">
		<!-- js -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
		<script src="/js/script.js"></script>
	</head>

	<body>
		<div class="container-fluid">
			<!-- header -->
			<div class="headerContainer row align-items-center">
			    <div class="col-xs-12 align-self-center">
					<header>
						<h1>Header</h1>
					</header>
				</div>
			</div>
			
			<!-- trunk -->
			<?php echo $this->block('trunk'); ?>
			
			<!-- footer -->
			<div class="footerContainer row align-items-center">
			    <div class="col-xs-12 align-self-center">
					<footer>
						<h3>Footer</h3>
					</footer>
				</div>
			</div>
		</div>
	</body>
	
</html>
